name: Build and release standalone binary of ecc

on:
    workflow_dispatch: 
    push:
      branches: ["*"]
      paths:
        - "ecli/**"
        - "compiler/**"
        - "wasm-rumtime/**"
        - "third_party/**"
        - "bpf-loader-rs/**"
        - "eunomia-sdk/**"
        - ".github/**"
  
    pull_request:
      branches: ["*"]
      paths:
        - "ecli/**"
        - "compiler/**"
        - "wasm-rumtime/**"
        - "third_party/**"
        - "bpf-loader-rs/**"
        - "eunomia-sdk/**"
        - ".github/**" 
env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local
  GITHUB_REPO_OWNER: ${{ github.repository_owner }}
    
jobs:
  create-release-version:
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.set_version.outputs.result}}
    steps:
      - name: Set latest release version
        id: set_version
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            const { data: tags } = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            if (releases.length === 0) { return "v0.0.1"; }
            
            function increase_v(version) {
              const parts = version.split(".");
              const last = parseInt(parts[2]) + 1;
              const next_version = `${parts[0]}.${parts[1]}.${last.toString()}`;
              return next_version;
            }
            
            const latest_release_tag = releases[0].tag_name;
            
            const tag = tags.find(tag => tag.commit.sha === context.sha);
            
            return tag ? tag.name : increase_v(latest_release_tag)
  
  build-ecc-binary:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: aarch64
            vmlinux_dir: arm64
            rust_target: aarch64-unknown-linux-gnu
            cross_compiler_package: gcc-aarch64-linux-gnu
            cross_compiler: aarch64-linux-gnu-gcc
            is_cross: true
            test_env: ubuntu18.04
          - name: x86_64
            vmlinux_dir: x86
            rust_target: x86_64-unknown-linux-gnu
            is_cross: false
            test_env: ubuntu:18.04
    name: Build ecc on ${{matrix.platform.name}}
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:20.04
      options: --privileged
    steps:
      - name: Prepare container environment
        run: |
          apt-get update
          apt-get install -y ca-certificates curl gnupg git sudo
          
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          
      - name: Setup Rust environment
        run: |
          . $HOME/.cargo/env
          rustup default stable
          rustup target add ${{matrix.platform.rust_target}}
      
      - name: Install LLVM and Clang for bindgen
        run: |
          apt-get install -y llvm-10 libclang-10-dev clang-10
      
      - name: Install dependencies for cross building
        if: matrix.platform.is_cross
        run: |
          apt-get install -y ${{matrix.platform.cross_compiler_package}}
          ${{matrix.platform.cross_compiler}} --version
      
      - name: Prepare bpftool and vmlinux repo for building workspace
        run: |
          mkdir workspace
          mkdir assets
          cd assets
          git clone --recursive https://github.com/eunomia-bpf/vmlinux
          cd vmlinux
          git checkout 933f83b
          rm vmlinux.h
          cd ..
          git clone --recursive https://github.com/eunomia-bpf/bpftool
      
      - name: Build workspace in docker
        uses: addnab/docker-run-action@v3
        if: "!matrix.platform.is_cross"
        with:
          image: ubuntu:20.04
          run: |
            apt-get update
            apt-get install -y zlib1g-dev libelf-dev gcc make
            cd /workspace && mkdir bin
            cd /assets/bpftool/src
            CFLAGS="-static" make
            cp bpftool /workspace/bin
          options: |
            --volume ${{github.workspace}}/workspace:/workspace
            --volume ${{github.workspace}}/assets:/assets
      
      - name: Build workspace in ${{matrix.platform.name}} virtual machine
        uses: uraimo/run-on-arch-action@v2
        if: matrix.platform.is_cross
        with: 
          arch: ${{matrix.platform.name}}
          distro: ubuntu20.04
          run: |
            apt-get update
            apt-get install -y zlib1g-dev libelf-dev gcc make
            cd /workspace && mkdir bin
            cd /assets/bpftool/src
            CFLAGS="-static" make
            cp bpftool /workspace/bin
          dockerRunArgs: |
            --volume "${PWD}/workspace:/workspace"
            --volume "${PWD}/assets:/assets"
      
      - name: Compose the ecc workspace
        run: |
          chmod 777 workspace -R
          chown `whoami` workspace -R
          cd workspace
          mkdir include
          cp -r ../assets/bpftool/src/libbpf/include/bpf include/
          cp -r ../assets/vmlinux/ include/
          cp ./include/vmlinux/${{matrix.platform.vmlinux_dir}}/vmlinux.h ./include/vmlinux
      
      - name: Build ecc for ${{matrix.platform.rust_target}}
        run: |
          . $HOME/.cargo/env
          export ECC_CUSTOM_WORKSPACE_ROOT=$(pwd)/workspace
          export LIBCLANG_PATH=/usr/lib/llvm-10/lib
          export LLVM_CONFIG_PATH=/usr/bin/llvm-config-10
          echo "Workspace dir: $ECC_CUSTOM_WORKSPACE_ROOT"
          cd compiler/cmd
          if [ "${{matrix.platform.is_cross}}" = "true" ]; then
            export CARGO_TARGET_$(echo ${{matrix.platform.rust_target}} | tr '[:lower:]' '[:upper:]' | tr '-' '_')_LINKER=${{matrix.platform.cross_compiler}}
          fi
          cargo build --release --target ${{matrix.platform.rust_target}}
          cd ../..
          mkdir -p output
          cp ./compiler/cmd/target/${{matrix.platform.rust_target}}/release/ecc-rs output/ecc-${{matrix.platform.name}}
          chmod +x output/ecc-${{matrix.platform.name}}
      
      - name: Verify glibc version requirement
        run: |
          if [ "${{matrix.platform.is_cross}}" = "false" ]; then
            apt-get install -y patchelf
            objdump -T output/ecc-${{matrix.platform.name}} | grep GLIBC_ | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -Vu | tail -1
          fi
      
      - name: Strip the binary
        run: |
          if [ "${{matrix.platform.is_cross}}" = "true" ]; then
            ${{matrix.platform.cross_compiler}} -s output/ecc-${{matrix.platform.name}} || true
          else
            strip output/ecc-${{matrix.platform.name}} || true
          fi
          ls -lh output/ecc-${{matrix.platform.name}}
      
      - uses: actions/upload-artifact@v4
        name: Upload build result
        with:
          name: ecc-${{matrix.platform.name}}
          path: output/ecc-${{matrix.platform.name}}
      
      - if: matrix.platform.is_cross
        continue-on-error: true
        name: Test the binary in a new environment (cross)
        uses: uraimo/run-on-arch-action@v2
        with: 
          arch: ${{matrix.platform.name}}
          distro: ${{matrix.platform.test_env}}
          run: |
            apt-get update
            apt-get install -y clang llvm-9
            cd /data
            chmod +x ecc-${{matrix.platform.name}}
            ./ecc-${{matrix.platform.name}} -l llvm-strip-9 .github/assets/simple.bpf.c
          dockerRunArgs: |
            --volume "${PWD}/output:/data" --privileged
      
      - name: Test the binary in a new environment (native)
        uses: addnab/docker-run-action@v3
        if: "!matrix.platform.is_cross"
        with:
          image: ${{matrix.platform.test_env}}
          run: |
            apt-get update
            apt-get install -y clang llvm-9
            cd /data
            chmod +x ecc-${{matrix.platform.name}}
            ./ecc-${{matrix.platform.name}} -l llvm-strip-9 .github/assets/simple.bpf.c
          options: |
            --volume ${{github.workspace}}/output:/data --privileged

  release:
    needs: [create-release-version, build-ecc-binary]
    runs-on: ubuntu-latest
    steps:
      - name: Download build results
        uses: actions/download-artifact@v4
        with:
          path: results
      
      - name: List build results
        run: |
          find ./results -type f
          file ./results/ecc-x86_64/ecc-x86_64 || true
          file ./results/ecc-aarch64/ecc-aarch64 || true
      
      - name: Copy ecc binary x86_64 to ecc
        run: |
          cp ./results/ecc-x86_64/ecc-x86_64 ./results/ecc-x86_64/ecc
      
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository_owner == 'eunomia-bpf'
        uses: softprops/action-gh-release@v1
        with:
            files: |
              ./results/ecc-x86_64/ecc
              ./results/ecc-x86_64/ecc-x86_64
              ./results/ecc-aarch64/ecc-aarch64
            prerelease: false
            tag_name: ${{ needs.create-release-version.outputs.version }}
            generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}